[package]
name = "quill-drivers"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
quill-core = { workspace = true }
anyhow = { workspace = true }
secrecy = { workspace = true }
tokio = { workspace = true }
datafusion-table-providers = { workspace = true, features = ["postgres"] }

[dev-dependencies]
url = { workspace = true }

[lints]
workspace = true
