[package]
name = "quill-drivers"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
quill-core = { workspace = true }
anyhow = { workspace = true }
secrecy = { workspace = true }
tokio = { workspace = true }
datafusion-table-providers = { workspace = true, optional = true }

[dev-dependencies]
url = { workspace = true }

[features]
default = []
postgres = [
    "dep:datafusion-table-providers",
    "datafusion-table-providers/postgres",
]

[lints]
workspace = true
